name: "Elixir Coverage Partitioned"
description: "Action to run tests, check coverage, and send a feedback message to the pull request."

branding:
  icon: "message-square"
  color: "purple"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  coverage_tool:
    description: "Coverage tool"
    default: "default"
    required: false
  coverage_threshold:
    description: "Coverage threshold"
    default: 90
    required: false
  working_directory:
    description: "Working directory"
    default: "."
    required: false

runs:
  using: "composite"
  steps:
    - name: Tests and coverage
      id: tests
      shell: bash
      env:
        ELASTICSEARCH_MAJOR_VERSION: ${{ matrix.elasticsearch_major_version }}
        ELASTICSEARCH_CLUSTER_0_MAJOR_VERSION: ${{ matrix.elasticsearch_major_version }}
        ELASTICSEARCH_CLUSTER_1_MAJOR_VERSION: ${{ matrix.elasticsearch_major_version }}
        DATABASE_URL: postgresql://turn:turn@localhost:5432/turn_dev_${{ matrix.partition }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MIX_TEST_PARTITION: ${{ matrix.partition }}
      run: |
        cd ${{ inputs.working_directory }}
        if mix test --cover --max-cases=1 --warnings-as-errors --partitions ${{ matrix.partition_count }} 2>&1 | tee coverage_report.log; then echo 'success running the tests'; fi

    - name: Feedback comment
      uses: actions/github-script@v6.4.1
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const actionPath = '${{ github.action_path }}';
          const coverageTool = '${{ inputs.coverage_tool }}'.toLowerCase();
          const actor = '${{ github.actor }}';

          const script = require(`${actionPath}/main.js`);
          await script({
            core,
            actor,
            github,
            context,
            coverageTool,
            coverageThreshold: ${{ inputs.coverage_threshold }},
            workingDirectory: '${{ inputs.working_directory }}',
          });
